#!/bin/bash
# wordstar, version 0.4.2
# copyright 2024 Erik Ben Heckman <erik@heckman.ca>
# shared under the terms of the MIT license


# wordstar: Launch WordStar in an emulated DOS environment on MacOS



set -euo pipefail

# don't use '~' in these paths as it won't necessarily be escaped
DOCUMENT_ROOT_PATH="$HOME/Documents/WordStar/"
DOS_ROOT_PATH="$HOME/Applications/WordStar/DOS root/"
DOSBOX_CONFIG_PATH="$HOME/Applications/WordStar/dosbox-x.conf"
DOSBOX_X_PATH="/Applications/dosbox-x.app/Contents/MacOS/dosbox-x"


# this enables accessing documents anywhere
# it still needs to be specified as a command line option
# unless the default value below is OPT_ALLOW_DOCUMENTS_ANYWHERE=true
ENABLE_ALLOWING_DOCUMENTS_ANYWHERE_AS_AN_OPTION=true

# default options, can be overridden by command line options
# change them to alter default behaviour
# if you change these, remember to update the defaults in help() as well
OPT_WORDSTAR_PRESET=WS
OPT_WORDSTAR_OPTION=''
OPT_FULLSCREEN=false
OPT_CREATE_MISSING_PATHS=false
OPT_ALLOW_DOCUMENTS_ANYWHERE=true
OPT_SHELL_ONLY=false

# these settings are relative the config file provided
# at /WS/DOSBox-X/dosbox-x.conf
# in Robert J. Sawyer's WordStar 7 Archive
# downloaded from https://sfwriter.com/ws7.htm
DOSBOX_ARGUMENTS=(
	-conf "$DOSBOX_CONFIG_PATH"
	-fastlaunch
	-noautoexec
	-set 'sdl fullscreen=false'
	-set 'ttf font=dejavusansmono'
	-set 'ttf fontbold=dejavusansmono-bold'
	-set 'ttf fontital=dejavusansmono-oblique'
	-set 'ttf fontboit=dejavusansmono-boldoblique'
	-set 'ttf ptsize=30'
	-set 'ttf lins=30'
	-set 'ttf cols=96'
	-c "@echo off"
	-c "mount -q C: \"${DOS_ROOT_PATH%/}\""
)

# it doesn't matter what drive letters are used here,
# as long as they're not C: or Z:
# and that they are not the same as each other.
DOCUMENT_DRIVE="D:" # this is also used for dynamic mount


# don't change the following options
DEBUG_DESTINATION=/dev/null



help(){
	echo "USAGE: wordstar [OPTIONS] [--] [DOCUMENT]

    Launches WordStar in an emulated DOS environment
    using Robert J. Sawyer's WordStar archive: https://sfwriter.com/ws7.htm


    OPTIONS THAT IGNORE ALL OTHER OPTIONS:

        -V, -version      Print version and copyright message and exit.
        -h, -help         Print this helpful message and exit.
        -hp, -paged-help  Open this helpful message in a pager.


    OPTIONS THAT SET WHAT TO LAUNCH IN THE EMULATOR:

        -dos, -shell      Don't launch WordStar, just launch DOSBox-X.
                          This is useful for testing etc.
        -pristine         Launch WordStar with an unmodified out-of-the-box
                          version of WordStar.
        -subdued          Launch WordStar with Robert J. Sawyer's custom
                          less-harsh colour scheme
        -sawyer           Launch WordStar with Robert J. Sawyer's preferred
                          layout and extensive cutomizations.
                          Default help level is 2.

        For descriptions of the presets, see the following file
        in Robert J. Sawyer's WordStar archive:
            '${DOS_ROOT_PATH%/}/WS/VERSIONS.TXT'


    OPTIONS THAT TWEAK WORDSTAR:

        -h4, -help4       Launch WordStar with \"Help Level 4\" (default).
        -h3, -help3       Launch WordStar with \"Help Level 3\".
        -h2, -help2       Launch WordStar with \"Help Level 2\".
        -h1, -help1       Launch WordStar with \"Help Level 1\".
        -h0, -help0       Launch WordStar with \"Help Level 0\".


    OPTIONS THAT TWEAK SCRIPT AND DOS EMULATOR:

        -v, -verbose      Be verbose: output dosbox-x debug messages.
        -f, -fullscreen   Start the emulation in full-screen mode.
        -w, -window       Start the emulation in windowed mode (default).
        -p, -path         If creating a new document, create its parent.
                          directories as required (not done by default).


    OPTIONS ALLOWING/RESTRICTING DIRECTORY MOUNTING:

        -d, -documents

            Restrict opening documents to the directory tree, the root of
            which is mounted as ${DOCUMENT_DRIVE%:}:, currently:
                ${DOCUMENT_ROOT_PATH%/}/
            Only files in this filesystem tree will be accessible.
            This is the only directory that can be mounted by,
            and is accessible to, DOSBox-X and WordStar.

            DOCUMENT is relative to the mounted document tree root.
            unless it begins with a / and resolves to a path that resides
            within the mounted document tree.

        -a, -any

            Allow documents from any directory to be opened.
            This will mount the document's parent directory in DOSBox-X,
            exposing it to both DOSBox-X and WordStar.

            This is the default behaviour.


    Each option must be specified in its own argument,
    i.e. they cannot be combined like '-pw', but should be '-p -w'.
    The long options can also be specified with two dashes.
    If multiple launch options are specified only the last one will be used.

    -- is required if DOCUMENT begins with a -.

    If DOCUMENT doesn't exist, a new document with the given name will
    will be opened in WordStar. The document's name appended with .WS if it
    doesn't already have that extension.

    ----------------------------------------------------------------------------

    For more information about WordStar, and Robert J. Sawyer's
    WordStar archive, see https://sfwriter.com/ws7.htm

    The archive is stored locally as:
        '${DOS_ROOT_PATH%/}/WS/'.

    Its README file can be found here:
        '${DOS_ROOT_PATH%/}/WS/-README.TXT'.


"
}


main(){
	while [[ "${1:0:1}" == '-' ]]
	do
		case "$1" in
		-V|-version|--version) version; exit;;  # ignore other options
		-h|-help|--help) help; exit;; # ignore other options
		-hp|-help-paged|--help-paged)
			help | ${PAGER:-/usr/bin/less}; exit;; # ignore other options
		-dos|--dos|-shell|--shell) shift;    OPT_SHELL_ONLY=true;;
		-h4|-help4|--help4) shift;           OPT_WORDSTAR_OPTION='/h4';;
		-h3|-help3|--help3) shift;           OPT_WORDSTAR_OPTION='/h3';;
		-h2|-help2|--help2) shift;           OPT_WORDSTAR_OPTION='/h2';;
		-h1|-help1|--help1) shift;           OPT_WORDSTAR_OPTION='/h1';;
		-h0|-help0|--help0) shift;           OPT_WORDSTAR_OPTION='/h0';;
		-subdued|--subdued) shift;           OPT_WORDSTAR_PRESET=WSRJS;;
		-sawyer|--sawyer) shift;             OPT_WORDSTAR_PRESET=SAWYER;;
		-pristine|--pristine) shift;         OPT_WORDSTAR_PRESET=PRISTINE;;
		-v|-verbose|--verbose) shift;        DEBUG_DESTINATION=/dev/stderr;;
		-w|-window*|--window*) shift;        OPT_FULLSCREEN=false;;
		-f|-fullscreen|--fullscreen) shift;  OPT_FULLSCREEN=true;;
		-p|-path|--path) shift;              OPT_CREATE_MISSING_PATHS=true;;
		-d|-documents|--documents) shift;    OPT_ALLOW_DOCUMENTS_ANYWHERE=false;;
		-a|-any*|--any*) shift
			if $ENABLE_ALLOWING_DOCUMENTS_ANYWHERE_AS_AN_OPTION
			then
				OPT_ALLOW_DOCUMENTS_ANYWHERE=true
			else
				die "Opening documents in any directory is disabled."
			fi
			;;
		--) shift; break;;
		-*) die "Unknown option: '$1', use -h for help.";;
		esac
	done

	$OPT_FULLSCREEN && DOSBOX_ARGUMENTS+=(-fullscreen)

	# determine mount_path, ws_document, and mount_drive
	local  mount_path ws_document
	if $OPT_ALLOW_DOCUMENTS_ANYWHERE
	then
		if [[ -d "${1:-.}" ]]
		then
			mount_path="${1%/}"
			ws_document=""
		else
			ws_document="$(
				basename "$(
					find_ws_document "$1"
				)" |
				reverse_slashes
			)"
			mount_path="$(dirname "$1")"
		fi
	else
		mount_path="${DOCUMENT_ROOT_PATH%/}"
		ws_document="$(
			strip_doc_dir "$(
				find_ws_document "$(
					prepend_doc_dir "${1:-}"
				)"
			)" |
			reverse_slashes
		)"
	fi

	# make sure mount_path exists
	[[ -d "$mount_path" ]] || die \
		"Directory '$mount_path' doesn't exist, use the -p option to create it."

	# add commands: mount the document drive and make it the working directory
	DOSBOX_ARGUMENTS+=(
		-c "mount -q ${DOCUMENT_DRIVE} \"${mount_path}\""
		-c "${DOCUMENT_DRIVE}"
	)

	if $OPT_SHELL_ONLY
	then
		# add commands for debugging purposes
		DOSBOX_ARGUMENTS+=(
			-c "set WS_DOCUMENT=${ws_document}"
			-c "mount ${DOCUMENT_DRIVE}"
			-c "echo WS_DOCUMENT is set to %WS_DOCUMENT%"
		)
	else
		# add commands: run WordStar with document then exit
		DOSBOX_ARGUMENTS+=(
			-c "$OPT_WORDSTAR_PRESET $OPT_WORDSTAR_OPTION ${ws_document}"
			-c "EXIT"
		)
	fi

	"$DOSBOX_X_PATH" "${DOSBOX_ARGUMENTS[@]}" 2>$DEBUG_DESTINATION
}

strip_doc_dir(){ local path="$1"
	echo "${path#"${DOCUMENT_ROOT_PATH%/}/"}"
}

prepend_doc_dir(){ local path; path="$(strip_doc_dir "$1")"
	echo "${DOCUMENT_ROOT_PATH%/}/${path}"
}

reverse_slashes(){
	sed 's|//*|\\|g'
}

find_ws_document(){ local path="$1"
	# check if the file exists, or if it exists when appending .WS extension
	# it's done the hard way in case the filesystem is case sensitive
	for ws_doc_path in "$path" "$path".[Ww][Ss]
	do
		if [[ -e "$ws_doc_path" ]]; then
			echo "$ws_doc_path"
			return
		fi
	done
	dirname "$path" >&2
	$OPT_CREATE_MISSING_PATHS && mkdir -p "$(dirname "$path")"
	# new document with WS extension
	echo "${path%.[Ww][Ss]}.WS"
}

version(){
	/usr/bin/awk '/^#!/{next}/^#/{sub("^# *","");print;next}{exit}' "$0"
}

die(){
	echo "$1">&2
	exit 77
}

main "$@"

